# Generated by Django 2.0.2 on 2018-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sutta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=50)),
                ('collection', models.CharField(max_length=4)),
                ('sutta_nr', models.SmallIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
