# Generated by Django 2.0.2 on 2018-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutta',
            name='title_pali',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
