# Generated by Django 2.0.2 on 2018-05-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_sutta_title_pali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutta',
            name='sutta_nr',
            field=models.CharField(max_length=10),
        ),
    ]
