# Generated by Django 2.0.2 on 2018-05-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180510_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sutta',
            name='collection',
            field=models.CharField(max_length=250),
        ),
    ]
